-- replace this with a lua version
-- return { "Lokaltog/vim-easymotion" }
return {
  "Lokaltog/vim-easymotion",
  -- {
  --   "phaazon/hop.nvim",
  --   branch = "v2", -- optional but strongly recommended
  --   config = function()
  --     local map = require("lazyvim").safe_keymap_set
  --     local hop = require("hop")
  --     local directions = require("hop.hint").HintDirection
  --
  --     hop.setup({ keys = "etovxqpdygfblzhckisuran" })
  --
  --     map("", "f", function()
  --       hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
  --     end, { desc = "Hop to character after cursor", remap = true })
  --
  --     map("", "F", function()
  --       hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
  --     end, { desc = "Hop to character before cursor", remap = true })
  --
  --     map("", "t", function()
  --       hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })
  --     end, { desc = "Hop to character after cursor with offset", remap = true })
  --
  --     map("", "T", function()
  --       hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })
  --     end, { desc = "Hop to character before cursor with offset", remap = true })
  --   end,
  -- },
}
